const divisions = [
  { id: crypto.randomUUID(), name: "Mobile Apps" },
  { id: crypto.randomUUID(), name: "QA" },
  { id: crypto.randomUUID(), name: "Full Stack" },
  { id: crypto.randomUUID(), name: "Backend" },
  { id: crypto.randomUUID(), name: "Frontend" },
  { id: crypto.randomUUID(), name: "UI/UX Designer" },
];

const dummyEmployees = [
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=budi.santoso",
    name: "Budi Santoso",
    email: "budi.santoso@gmail.com",
    phone: "081234567890",
    division: {
      id: "5",
      name: "Frontend",
    },
    position: "Senior Frontend Developer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=citra.lestari",
    name: "Citra Lestari",
    email: "citra.lestari@gmail.com",
    phone: "082345678901",
    division: {
      id: "6",
      name: "UI/UX Designer",
    },
    position: "Lead UI/UX Designer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=agus.purnomo",
    name: "Agus Purnomo",
    email: "agus.purnomo@gmail.com",
    phone: "083456789012",
    division: {
      id: "4",
      name: "Backend",
    },
    position: "Backend Developer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=diana.sari",
    name: "Diana Sari",
    email: "diana.sari@gmail.com",
    phone: "084567890123",
    division: {
      id: "2",
      name: "QA",
    },
    position: "Quality Assurance Engineer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=eko.prasetyo",
    name: "Eko Prasetyo",
    email: "eko.prasetyo@gmail.com",
    phone: "085678901234",
    division: {
      id: "3",
      name: "Full Stack",
    },
    position: "Full Stack Developer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=fitri.rahayu",
    name: "Fitri Rahayu",
    email: "fitri.rahayu@gmail.com",
    phone: "086789012345",
    division: {
      id: "1",
      name: "Mobile Apps",
    },
    position: "Android Developer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=galih.wijaya",
    name: "Galih Wijaya",
    email: "galih.wijaya@gmail.com",
    phone: "087890123456",
    division: {
      id: "4",
      name: "Backend",
    },
    position: "Senior Backend Developer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=indah.permatasari",
    name: "Indah Permatasari",
    email: "indah.permatasari@gmail.com",
    phone: "088901234567",
    division: {
      id: "5",
      name: "Frontend",
    },
    position: "Junior Frontend Developer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=joko.susilo",
    name: "Joko Susilo",
    email: "joko.susilo@gmail.com",
    phone: "089012345678",
    division: {
      id: "3",
      name: "Full Stack",
    },
    position: "Tech Lead",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=kartika.dewi",
    name: "Kartika Dewi",
    email: "kartika.dewi@gmail.com",
    phone: "081123456789",
    division: {
      id: "6",
      name: "UI/UX Designer",
    },
    position: "UI/UX Researcher",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=lukman.hakim",
    name: "Lukman Hakim",
    email: "lukman.hakim@gmail.com",
    phone: "082234567890",
    division: {
      id: "1",
      name: "Mobile Apps",
    },
    position: "iOS Developer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=maya.andini",
    name: "Maya Andini",
    email: "maya.andini@gmail.com",
    phone: "083345678901",
    division: {
      id: "2",
      name: "QA",
    },
    position: "Automation QA Engineer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=nina.rosita",
    name: "Nina Rosita",
    email: "nina.rosita@gmail.com",
    phone: "084456789012",
    division: {
      id: "5",
      name: "Frontend",
    },
    position: "Frontend Developer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=rendi.saputra",
    name: "Rendi Saputra",
    email: "rendi.saputra@gmail.com",
    phone: "085567890123",
    division: {
      id: "4",
      name: "Backend",
    },
    position: "Database Administrator",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=sari.wulandari",
    name: "Sari Wulandari",
    email: "sari.wulandari@gmail.com",
    phone: "086678901234",
    division: {
      id: "6",
      name: "UI/UX Designer",
    },
    position: "UI Designer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=tono.marjono",
    name: "Tono Marjono",
    email: "tono.marjono@gmail.com",
    phone: "087789012345",
    division: {
      id: "3",
      name: "Full Stack",
    },
    position: "Junior Full Stack Developer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=vera.oktavia",
    name: "Vera Oktavia",
    email: "vera.oktavia@gmail.com",
    phone: "088890123456",
    division: {
      id: "2",
      name: "QA",
    },
    position: "Manual QA Tester",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=yudi.gunawan",
    name: "Yudi Gunawan",
    email: "yudi.gunawan@gmail.com",
    phone: "089901234567",
    division: {
      id: "1",
      name: "Mobile Apps",
    },
    position: "React Native Developer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=zainal.arifin",
    name: "Zainal Arifin",
    email: "zainal.arifin@gmail.com",
    phone: "081345678901",
    division: {
      id: "4",
      name: "Backend",
    },
    position: "DevOps Engineer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=anisa.rahmawati",
    name: "Anisa Rahmawati",
    email: "anisa.rahmawati@gmail.com",
    phone: "082456789012",
    division: {
      id: "5",
      name: "Frontend",
    },
    position: "UI Engineer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=andi.wijaya",
    name: "Andi Wijaya",
    email: "andi.wijaya@gmail.com",
    phone: "082423064725",
    division: { id: "6", name: "UI/UX Designer" },
    position: "QA Tester",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=bella.putri",
    name: "Bella Putri",
    email: "bella.putri@gmail.com",
    phone: "088731778139",
    division: { id: "2", name: "QA" },
    position: "UI/UX Researcher",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=cahyo.nugroho",
    name: "Cahyo Nugroho",
    email: "cahyo.nugroho@gmail.com",
    phone: "087592263312",
    division: { id: "5", name: "Frontend" },
    position: "Full Stack Developer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=dewi.sartika",
    name: "Dewi Sartika",
    email: "dewi.sartika@gmail.com",
    phone: "084396849432",
    division: { id: "3", name: "Full Stack" },
    position: "Junior Developer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=evan.mahendra",
    name: "Evan Mahendra",
    email: "evan.mahendra@gmail.com",
    phone: "088155280974",
    division: { id: "2", name: "QA" },
    position: "Product Designer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=fika.lestari",
    name: "Fika Lestari",
    email: "fika.lestari@gmail.com",
    phone: "087678901331",
    division: { id: "4", name: "Backend" },
    position: "Product Designer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=gilang.prakoso",
    name: "Gilang Prakoso",
    email: "gilang.prakoso@gmail.com",
    phone: "084726900798",
    division: { id: "4", name: "Backend" },
    position: "Full Stack Developer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=hesti.rahayu",
    name: "Hesti Rahayu",
    email: "hesti.rahayu@gmail.com",
    phone: "082629433569",
    division: { id: "2", name: "QA" },
    position: "Automation QA Engineer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=irfan.syah",
    name: "Irfan Syah",
    email: "irfan.syah@gmail.com",
    phone: "087923051327",
    division: { id: "5", name: "Frontend" },
    position: "Backend Developer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=jihan.nabila",
    name: "Jihan Nabila",
    email: "jihan.nabila@gmail.com",
    phone: "084946251200",
    division: { id: "3", name: "Full Stack" },
    position: "Mobile Developer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=kevin.saputra",
    name: "Kevin Saputra",
    email: "kevin.saputra@gmail.com",
    phone: "087634323112",
    division: { id: "4", name: "Backend" },
    position: "UX Designer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=larasati.dewi",
    name: "Larasati Dewi",
    email: "larasati.dewi@gmail.com",
    phone: "081370777563",
    division: { id: "2", name: "QA" },
    position: "Full Stack Developer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=muhammad.fahri",
    name: "Muhammad Fahri",
    email: "muhammad.fahri@gmail.com",
    phone: "083594838298",
    division: { id: "4", name: "Backend" },
    position: "Product Designer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=nadia.fitri",
    name: "Nadia Fitri",
    email: "nadia.fitri@gmail.com",
    phone: "085193779661",
    division: { id: "5", name: "Frontend" },
    position: "UI Designer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=oscar.yudha",
    name: "Oscar Yudha",
    email: "oscar.yudha@gmail.com",
    phone: "082265029628",
    division: { id: "1", name: "Mobile Apps" },
    position: "Frontend Developer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=putri.anggraini",
    name: "Putri Anggraini",
    email: "putri.anggraini@gmail.com",
    phone: "087552618457",
    division: { id: "1", name: "Mobile Apps" },
    position: "Software Engineer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=raka.perdana",
    name: "Raka Perdana",
    email: "raka.perdana@gmail.com",
    phone: "089787048462",
    division: { id: "6", name: "UI/UX Designer" },
    position: "Mid Developer",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=sinta.aprilia",
    name: "Sinta Aprilia",
    email: "sinta.aprilia@gmail.com",
    phone: "084778855736",
    division: { id: "2", name: "QA" },
    position: "QA Tester",
  },
  {
    id: crypto.randomUUID(),
    image: "https://i.pravatar.cc/150?u=tegar.wibowo",
    name: "Tegar Wibowo",
    email: "tegar.wibowo@gmail.com",
    phone: "083452173979",
    division: { id: "1", name: "Mobile Apps" },
    position: "DevOps Engineer",
  },
];

export { divisions, dummyEmployees };
