const divisions = [
  { id: 1, name: "Mobile Apps" },
  { id: 2, name: "QA" },
  { id: 3, name: "Full Stack" },
  { id: 4, name: "Backend" },
  { id: 5, name: "Frontend" },
  { id: 6, name: "UI/UX Designer" },
];

const dummyEmployees = [
  {
    id: "2",
    image: "https://i.pravatar.cc/150?u=budi.santoso",
    name: "Budi Santoso",
    phone: "081234567890",
    division: {
      id: "5",
      name: "Frontend",
    },
    position: "Senior Frontend Developer",
  },
  {
    id: "3",
    image: "https://i.pravatar.cc/150?u=citra.lestari",
    name: "Citra Lestari",
    phone: "082345678901",
    division: {
      id: "6",
      name: "UI/UX Designer",
    },
    position: "Lead UI/UX Designer",
  },
  {
    id: "4",
    image: "https://i.pravatar.cc/150?u=agus.purnomo",
    name: "Agus Purnomo",
    phone: "083456789012",
    division: {
      id: "4",
      name: "Backend",
    },
    position: "Backend Developer",
  },
  {
    id: "5",
    image: "https://i.pravatar.cc/150?u=diana.sari",
    name: "Diana Sari",
    phone: "084567890123",
    division: {
      id: "2",
      name: "QA",
    },
    position: "Quality Assurance Engineer",
  },
  {
    id: "6",
    image: "https://i.pravatar.cc/150?u=eko.prasetyo",
    name: "Eko Prasetyo",
    phone: "085678901234",
    division: {
      id: "3",
      name: "Full Stack",
    },
    position: "Full Stack Developer",
  },
  {
    id: "7",
    image: "https://i.pravatar.cc/150?u=fitri.rahayu",
    name: "Fitri Rahayu",
    phone: "086789012345",
    division: {
      id: "1",
      name: "Mobile Apps",
    },
    position: "Android Developer",
  },
  {
    id: "8",
    image: "https://i.pravatar.cc/150?u=galih.wijaya",
    name: "Galih Wijaya",
    phone: "087890123456",
    division: {
      id: "4",
      name: "Backend",
    },
    position: "Senior Backend Developer",
  },
  {
    id: "9",
    image: "https://i.pravatar.cc/150?u=indah.permatasari",
    name: "Indah Permatasari",
    phone: "088901234567",
    division: {
      id: "5",
      name: "Frontend",
    },
    position: "Junior Frontend Developer",
  },
  {
    id: "10",
    image: "https://i.pravatar.cc/150?u=joko.susilo",
    name: "Joko Susilo",
    phone: "089012345678",
    division: {
      id: "3",
      name: "Full Stack",
    },
    position: "Tech Lead",
  },
  {
    id: "11",
    image: "https://i.pravatar.cc/150?u=kartika.dewi",
    name: "Kartika Dewi",
    phone: "081123456789",
    division: {
      id: "6",
      name: "UI/UX Designer",
    },
    position: "UI/UX Researcher",
  },
  {
    id: "12",
    image: "https://i.pravatar.cc/150?u=lukman.hakim",
    name: "Lukman Hakim",
    phone: "082234567890",
    division: {
      id: "1",
      name: "Mobile Apps",
    },
    position: "iOS Developer",
  },
  {
    id: "13",
    image: "https://i.pravatar.cc/150?u=maya.andini",
    name: "Maya Andini",
    phone: "083345678901",
    division: {
      id: "2",
      name: "QA",
    },
    position: "Automation QA Engineer",
  },
  {
    id: "14",
    image: "https://i.pravatar.cc/150?u=nina.rosita",
    name: "Nina Rosita",
    phone: "084456789012",
    division: {
      id: "5",
      name: "Frontend",
    },
    position: "Frontend Developer",
  },
  {
    id: "15",
    image: "https://i.pravatar.cc/150?u=rendi.saputra",
    name: "Rendi Saputra",
    phone: "085567890123",
    division: {
      id: "4",
      name: "Backend",
    },
    position: "Database Administrator",
  },
  {
    id: "16",
    image: "https://i.pravatar.cc/150?u=sari.wulandari",
    name: "Sari Wulandari",
    phone: "086678901234",
    division: {
      id: "6",
      name: "UI/UX Designer",
    },
    position: "UI Designer",
  },
  {
    id: "17",
    image: "https://i.pravatar.cc/150?u=tono.marjono",
    name: "Tono Marjono",
    phone: "087789012345",
    division: {
      id: "3",
      name: "Full Stack",
    },
    position: "Junior Full Stack Developer",
  },
  {
    id: "18",
    image: "https://i.pravatar.cc/150?u=vera.oktavia",
    name: "Vera Oktavia",
    phone: "088890123456",
    division: {
      id: "2",
      name: "QA",
    },
    position: "Manual QA Tester",
  },
  {
    id: "19",
    image: "https://i.pravatar.cc/150?u=yudi.gunawan",
    name: "Yudi Gunawan",
    phone: "089901234567",
    division: {
      id: "1",
      name: "Mobile Apps",
    },
    position: "React Native Developer",
  },
  {
    id: "20",
    image: "https://i.pravatar.cc/150?u=zainal.arifin",
    name: "Zainal Arifin",
    phone: "081345678901",
    division: {
      id: "4",
      name: "Backend",
    },
    position: "DevOps Engineer",
  },
  {
    id: "21",
    image: "https://i.pravatar.cc/150?u=anisa.rahmawati",
    name: "Anisa Rahmawati",
    phone: "082456789012",
    division: {
      id: "5",
      name: "Frontend",
    },
    position: "UI Engineer",
  },
  {
    id: "22",
    image: "https://i.pravatar.cc/150?u=andi.wijaya",
    name: "Andi Wijaya",
    phone: "082423064725",
    division: { id: "6", name: "UI/UX Designer" },
    position: "QA Tester",
  },
  {
    id: "23",
    image: "https://i.pravatar.cc/150?u=bella.putri",
    name: "Bella Putri",
    phone: "088731778139",
    division: { id: "2", name: "QA" },
    position: "UI/UX Researcher",
  },
  {
    id: "24",
    image: "https://i.pravatar.cc/150?u=cahyo.nugroho",
    name: "Cahyo Nugroho",
    phone: "087592263312",
    division: { id: "5", name: "Frontend" },
    position: "Full Stack Developer",
  },
  {
    id: "25",
    image: "https://i.pravatar.cc/150?u=dewi.sartika",
    name: "Dewi Sartika",
    phone: "084396849432",
    division: { id: "3", name: "Full Stack" },
    position: "Junior Developer",
  },
  {
    id: "26",
    image: "https://i.pravatar.cc/150?u=evan.mahendra",
    name: "Evan Mahendra",
    phone: "088155280974",
    division: { id: "2", name: "QA" },
    position: "Product Designer",
  },
  {
    id: "27",
    image: "https://i.pravatar.cc/150?u=fika.lestari",
    name: "Fika Lestari",
    phone: "087678901331",
    division: { id: "4", name: "Backend" },
    position: "Product Designer",
  },
  {
    id: "28",
    image: "https://i.pravatar.cc/150?u=gilang.prakoso",
    name: "Gilang Prakoso",
    phone: "084726900798",
    division: { id: "4", name: "Backend" },
    position: "Full Stack Developer",
  },
  {
    id: "29",
    image: "https://i.pravatar.cc/150?u=hesti.rahayu",
    name: "Hesti Rahayu",
    phone: "082629433569",
    division: { id: "2", name: "QA" },
    position: "Automation QA Engineer",
  },
  {
    id: "30",
    image: "https://i.pravatar.cc/150?u=irfan.syah",
    name: "Irfan Syah",
    phone: "087923051327",
    division: { id: "5", name: "Frontend" },
    position: "Backend Developer",
  },
  {
    id: "31",
    image: "https://i.pravatar.cc/150?u=jihan.nabila",
    name: "Jihan Nabila",
    phone: "084946251200",
    division: { id: "3", name: "Full Stack" },
    position: "Mobile Developer",
  },
  {
    id: "32",
    image: "https://i.pravatar.cc/150?u=kevin.saputra",
    name: "Kevin Saputra",
    phone: "087634323112",
    division: { id: "4", name: "Backend" },
    position: "UX Designer",
  },
  {
    id: "33",
    image: "https://i.pravatar.cc/150?u=larasati.dewi",
    name: "Larasati Dewi",
    phone: "081370777563",
    division: { id: "2", name: "QA" },
    position: "Full Stack Developer",
  },
  {
    id: "34",
    image: "https://i.pravatar.cc/150?u=muhammad.fahri",
    name: "Muhammad Fahri",
    phone: "083594838298",
    division: { id: "4", name: "Backend" },
    position: "Product Designer",
  },
  {
    id: "35",
    image: "https://i.pravatar.cc/150?u=nadia.fitri",
    name: "Nadia Fitri",
    phone: "085193779661",
    division: { id: "5", name: "Frontend" },
    position: "UI Designer",
  },
  {
    id: "36",
    image: "https://i.pravatar.cc/150?u=oscar.yudha",
    name: "Oscar Yudha",
    phone: "082265029628",
    division: { id: "1", name: "Mobile Apps" },
    position: "Frontend Developer",
  },
  {
    id: "37",
    image: "https://i.pravatar.cc/150?u=putri.anggraini",
    name: "Putri Anggraini",
    phone: "087552618457",
    division: { id: "1", name: "Mobile Apps" },
    position: "Software Engineer",
  },
  {
    id: "38",
    image: "https://i.pravatar.cc/150?u=raka.perdana",
    name: "Raka Perdana",
    phone: "089787048462",
    division: { id: "6", name: "UI/UX Designer" },
    position: "Mid Developer",
  },
  {
    id: "39",
    image: "https://i.pravatar.cc/150?u=sinta.aprilia",
    name: "Sinta Aprilia",
    phone: "084778855736",
    division: { id: "2", name: "QA" },
    position: "QA Tester",
  },
  {
    id: "40",
    image: "https://i.pravatar.cc/150?u=tegar.wibowo",
    name: "Tegar Wibowo",
    phone: "083452173979",
    division: { id: "1", name: "Mobile Apps" },
    position: "DevOps Engineer",
  },
];

export { divisions, dummyEmployees };
